### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by JaPNaA** [BlueMonkeys/Number_Guessing_Game#1]
I’m typing this on my iPad just before I go to sleep, so it’s not going to be as detailed as the last one, but this one also has much fewer lines for me to pick on.

#### Use `for` loops instead of `do while`

There is no reason to not.

It’s cleaner, uses less code, and is easier to read.

```java
for (int i = 0; i < timesToLoop; i++) {
  // your code (loops timesToLoop times)
}
```
 #### Use `try catch`

```java
try {
  // code that could potentially throw errors... like
  sc.nextInt(); // which could throw a mismatch exception
} catch (Exception e) {
  // code called when an error occurs in the try block
}
```

#### Use local variables

Instead of all of your variables being declared in the class.

This, like `private` should be used wherever possible. Less bugs, cleaner code.

#### Correct formatting
Looks like something I would write!

#### Between 1 and 100, inclusive
Lol

#### All possible ints covered

---

### Some things that I noticed
  - The first 2 static members didn’t have a public/private identifier, and is therefore private by default
  - Lines 37 to 38 could have been optimized (very very slightly) by doing one `println` and using a `"\n"` as a newline separator
  - I don't think you need `String[] args` if you don't need to get any command line arguments.

**Comment by JaPNaA** [comment]
Also I'm going to make sure you see my program proposal

https://github.com/BlueMonkeys/Number_Guessing_Game/commit/a858985d386ef9e69d08d1ea4527c7814c77d85e#commitcomment-32295511

**Comment by AP090** [comment]
Is it preferred to the \n to allow large blocks of text in one command?

**Comment by JaPNaA** [comment]
I don't understand what you mean.
They're pretty much the same, except `\n` takes less time to run.

**Fine**
```java
for (int i = 0; i < 100; i++) {
    System.out.println(i);
}
```

**Not fine**
```java
System.out.println("This is the first thing I print");
System.out.println("This is the second thing I print");
System.out.println("This is the third thing I print");
```

**Prefered** (for me) (note: if your also printing variables, you may want to consider StringBuilder for performance issues (or just putting it in a different println))
```java
System.out.println(
    "This is the first thing I print\n" +
    "This is still the first thing I print\n" +
    "Still the same! Just with newlines!"
);
```
